import requests
from bs4 import BeautifulSoup

coin_urls = {
    '1921':{'10 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12572.asp', '15 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12766.asp', '20 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12952.asp', '50 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13141.asp', '1 рубль': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13210.asp'},
    '1922':{'10 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12573.asp', '15 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12767.asp', '20 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12955.asp', '50 копеек ПЛ': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13143.asp', '50 копеек АГ': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13142.asp', '1 рубль ПЛ': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13215.asp', '1 рубль АГ': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13213.asp'},
    '1923':{'10 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12574.asp', '15 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12769.asp', '20 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12957.asp'},
    '1924':{'1 копейка гурт рубчатый': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr11812.asp', '1 копейка гурт гладкий': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr11813.asp', '2 копейки гурт рубчатый': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12012.asp', '2 копейки гурт гладкий': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12013.asp', '3 копейки гурт рубчатый': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12179.asp', '3 копейки гурт гладкий': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12182.asp', '5 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12413.asp', '10 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12575.asp', '15 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12770.asp', '20 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12959.asp', '50 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13155.asp', '1 рубль': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13218.asp'},
    '1925':{'Полкопейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr11986.asp', '1 копейка': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr11817.asp', '2 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12019.asp', '10 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12576.asp', '15 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12777.asp', '20 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12962.asp', '50 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13161.asp'},
    '1926':{'1 копейка': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr11820.asp', '2 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12022.asp', '3 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12187.asp', '5 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12420.asp', '50 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13164.asp'},
    '1927':{'Полкопейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr11987.asp', '1 копейка': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr11822.asp', '2 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12023.asp', '3 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12191.asp', '5 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12425.asp', '10 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12578.asp', '15 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12804.asp', '20 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12965.asp', '50 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13166.asp'},
    '1928':{'Полкопейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr11988.asp', '1 копейка': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr11825.asp', '2 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12024.asp', '3 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12193.asp', '5 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12426.asp', '10 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12587.asp', '15 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12806.asp', '20 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12966.asp'},
    '1929':{'1 копейка': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr11827.asp', '2 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12027.asp', '3 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12195.asp', '5 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12428.asp', '10 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12619.asp', '15 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12810.asp', '20 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12968.asp'},
    '1930':{'1 копейка': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr11828.asp', '2 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12028.asp', '3 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12197.asp', '5 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12429.asp', '10 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12624.asp', '15 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12811.asp', '20 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12970.asp'},
    '1931':{'1 копейка': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr11830.asp', '2 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12030.asp', '3 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12199.asp', '5 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12431.asp', '10 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12626.asp', '15 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12813.asp', '20 копеек мельхиор': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12973.asp', '20 копеек серебро': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12972.asp'},
    '1932':{'1 копейка': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr11831.asp', '2 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12032.asp', '3 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12203.asp', '5 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12433.asp', '10 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12631.asp', '15 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12820.asp', '20 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12980.asp'},
    '1933':{'1 копейка': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr11835.asp', '2 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12035.asp', '3 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12206.asp', '5 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12434.asp', '10 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12634.asp', '15 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12823.asp', '20 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12984.asp'},
    '1934':{'1 копейка': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr11836.asp', '2 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12037.asp', '3 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12209.asp', '5 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12438.asp', '10 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12638.asp', '15 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12826.asp'},
    '1935':{'1 копейка старый тип': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr11838.asp', '1 копейка новый тип': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr11841.asp', '2 копейки старый тип': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12039.asp', '2 копейки новый тип': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12041.asp', '3 копейки старый тип': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12212.asp', '3 копейки новый тип': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12217.asp', '5 копеек старый тип': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12441.asp', '5 копеек новый тип': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12445.asp', '10 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12640.asp', '15 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12829.asp', '20 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12987.asp'},
    '1936':{'1 копейка': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr11845.asp', '2 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12053.asp', '3 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12222.asp', '5 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12452.asp', '10 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12643.asp', '15 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12835.asp', '20 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12990.asp'},
    '1937':{'1 копейка': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr11855.asp', '2 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12058.asp', '3 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12227.asp', '5 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12456.asp', '10 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12645.asp', '15 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12838.asp', '20 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12993.asp'},
    '1938':{'1 копейка': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr11870.asp', '2 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12060.asp', '3 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12235.asp', '5 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12459.asp', '10 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12650.asp', '15 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12840.asp', '20 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12996.asp'},
    '1939':{'1 копейка': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr11883.asp', '2 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12070.asp', '3 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12242.asp', '5 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12460.asp', '10 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12653.asp', '15 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12842.asp', '20 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13000.asp'},
    '1940':{'1 копейка': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr11892.asp', '2 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12080.asp', '3 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12251.asp', '5 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12464.asp', '10 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12655.asp', '15 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12844.asp', '20 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13002.asp'},
    '1941':{'1 копейка': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr11900.asp', '2 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12095.asp', '3 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12258.asp', '5 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12469.asp', '10 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12657.asp', '15 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12846.asp', '20 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13005.asp'},
    '1942':{'10 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12659.asp', '15 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12848.asp', '20 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13010.asp'},
    '1943':{'3 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12263.asp', '5 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12473.asp', '10 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12661.asp', '15 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12858.asp', '20 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13015.asp'},
    '1944':{'10 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12668.asp', '15 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12861.asp', '20 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13027.asp'},
    '1945':{'1 копейка': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr11905.asp', '2 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12099.asp', '3 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12266.asp', '5 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12475.asp', '10 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12674.asp', '15 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12862.asp', '20 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13030.asp'},
    '1946':{'1 копейка': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr11906.asp', '2 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12101.asp', '3 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12271.asp', '5 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12477.asp', '10 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12680.asp', '15 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12869.asp', '20 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13032.asp'},
    '1948':{'1 копейка': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr11909.asp', '2 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12107.asp', '3 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12279.asp', '5 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12480.asp', '10 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12682.asp', '15 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12881.asp', '20 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13040.asp'},
    '1949':{'1 копейка': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr11910.asp', '2 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12109.asp', '3 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12285.asp', '5 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12482.asp', '10 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12688.asp', '15 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12885.asp', '20 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13044.asp'},
    '1950':{'1 копейка': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr11914.asp', '2 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12116.asp', '3 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12291.asp', '5 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12485.asp', '10 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12695.asp', '15 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12888.asp', '20 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13050.asp'},
    '1951':{'1 копейка': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr11916.asp', '2 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12117.asp', '3 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12295.asp', '5 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12493.asp', '10 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12696.asp', '15 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12890.asp', '20 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13053.asp'},
    '1952':{'1 копейка': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr11917.asp', '2 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12119.asp', '3 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12307.asp', '5 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12510.asp', '10 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12699.asp', '15 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12898.asp', '20 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13056.asp'},
    '1953':{'1 копейка': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr11921.asp', '2 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12121.asp', '3 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12314.asp', '5 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12519.asp', '10 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12703.asp', '15 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12903.asp', '20 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13060.asp'},
    '1954':{'1 копейка': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr11922.asp', '2 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12122.asp', '3 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12318.asp', '5 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12520.asp', '10 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12704.asp', '15 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12905.asp', '20 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13062.asp'},
    '1955':{'1 копейка': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr11923.asp', '2 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12123.asp', '3 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12320.asp', '5 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12522.asp', '10 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12705.asp', '15 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12907.asp', '20 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13065.asp'},
    '1956':{'1 копейка': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr11925.asp', '2 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12125.asp', '3 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12321.asp', '5 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12523.asp', '10 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12706.asp', '15 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12909.asp', '20 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13067.asp'},
    '1957':{'1 копейка': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr11927.asp', '2 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12126.asp', '3 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12323.asp', '5 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12524.asp', '10 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12709.asp', '15 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12910.asp', '20 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13068.asp'},
    '1958':{'1 копейка': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr11930.asp', '2 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12128.asp', '3 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12325.asp', '5 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12527.asp', '10 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12711.asp', '15 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12912.asp', '20 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13074.asp', '50 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13167.asp', '1 рубль': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13221.asp', '2 рубля': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13259.asp', '3 рубля': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13260.asp', '5 рублей': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13261.asp'},
    '1961':{'1 копейка': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr11933.asp', '2 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12130.asp', '3 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12326.asp', '5 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12528.asp', '10 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12713.asp', '15 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12913.asp', '20 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13075.asp', '50 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13169.asp', '1 рубль': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13222.asp'},
    '1962':{'1 копейка': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr11937.asp', '2 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12131.asp', '3 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12331.asp', '5 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12533.asp', '10 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12715.asp', '15 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12914.asp', '20 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13078.asp'},
    '1963':{'1 копейка': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr11938.asp', '2 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12132.asp'},
    '1964':{'1 копейка': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr11940.asp', '2 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12134.asp', '50 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13170.asp', '1 рубль': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13223.asp'},
    '1965':{'1 копейка': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr11941.asp', '2 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12135.asp', '3 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12333.asp', '5 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12535.asp', '10 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12716.asp', '15 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12915.asp', '20 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13079.asp', '50 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13171.asp', '1 рубль': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13224.asp'},
    '1966':{'1 копейка': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr11942.asp', '2 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12136.asp', '3 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12335.asp', '5 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12536.asp', '10 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12717.asp', '15 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12916.asp', '20 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13080.asp', '50 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13172.asp', '1 рубль': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13225.asp'},
    '1967':{'1 копейка': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr11947.asp', '2 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12137.asp', '3 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12338.asp', '5 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12537.asp', '10 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12718.asp', '15 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12917.asp', '20 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13081.asp', '50 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13173.asp', '1 рубль': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13226.asp'},
    '1968':{'1 копейка': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr11949.asp', '2 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12138.asp', '3 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12339.asp', '5 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12538.asp', '10 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12719.asp', '15 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12918.asp', '20 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13082.asp', '50 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13174.asp', '1 рубль': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13228.asp'},
    '1969':{'1 копейка': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr11950.asp', '2 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12139.asp', '3 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12340.asp', '5 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12539.asp', '10 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12720.asp', '15 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12919.asp', '20 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13083.asp', '50 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13175.asp', '1 рубль': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13229.asp'},
    '1970':{'1 копейка': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr11951.asp', '2 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12140.asp', '3 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12341.asp', '5 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12540.asp', '10 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12721.asp', '15 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12920.asp', '20 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13084.asp', '50 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13176.asp', '1 рубль': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13230.asp'},
    '1971':{'1 копейка': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr11952.asp', '2 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12141.asp', '3 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12342.asp', '5 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12541.asp', '10 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12722.asp', '15 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12921.asp', '20 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13085.asp', '50 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13177.asp', '1 рубль': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13231.asp'},
    '1972':{'1 копейка': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr11953.asp', '2 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12142.asp', '3 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12344.asp', '5 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12542.asp', '10 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12723.asp', '15 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12922.asp', '20 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13086.asp', '50 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13178.asp', '1 рубль': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13232.asp'},
    '1973':{'1 копейка': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr11954.asp', '2 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12146.asp', '3 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12348.asp', '5 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12543.asp', '10 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12724.asp', '15 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12923.asp', '20 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13088.asp', '50 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13179.asp', '1 рубль': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13233.asp'},
    '1974':{'1 копейка': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr11956.asp', '2 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12149.asp', '3 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12350.asp', '5 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12544.asp', '10 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12725.asp', '15 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12924.asp', '20 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13089.asp', '50 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13180.asp', '1 рубль': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13234.asp'},
    '1975':{'1 копейка': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr11958.asp', '2 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12150.asp', '3 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12352.asp', '5 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12545.asp', '10 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12726.asp', '15 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12925.asp', '20 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13091.asp', '50 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13181.asp', '1 рубль': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13235.asp'},
    '1976':{'1 копейка': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr11959.asp', '2 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12151.asp', '3 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12353.asp', '5 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12546.asp', '10 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12727.asp', '15 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12926.asp', '20 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13092.asp', '50 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13182.asp', '1 рубль': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13236.asp'},
    '1977':{'1 копейка': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr11960.asp', '2 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12154.asp', '3 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12357.asp', '5 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12548.asp', '10 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12730.asp', '15 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12927.asp', '20 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13093.asp', '50 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13184.asp', '1 рубль': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13238.asp'},
    '1978':{'1 копейка': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr11961.asp', '2 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12156.asp', '3 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12362.asp', '5 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12551.asp', '10 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12735.asp', '15 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12928.asp', '20 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13095.asp', '50 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13187.asp', '1 рубль': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13239.asp'},
    '1979':{'1 копейка': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr11962.asp', '2 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12159.asp', '3 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12367.asp', '5 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12553.asp', '10 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12738.asp', '15 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12929.asp', '20 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13097.asp', '50 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13189.asp', '1 рубль': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13241.asp'},
    '1980':{'1 копейка': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr11963.asp', '2 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12160.asp', '3 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12370.asp', '5 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12554.asp', '10 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12739.asp', '15 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12930.asp', '20 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13100.asp', '50 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13190.asp', '1 рубль': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13242.asp'},
    '1981':{'1 копейка': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr11966.asp', '2 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12161.asp', '3 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12373.asp', '5 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12556.asp', '10 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12741.asp', '15 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12932.asp', '20 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13105.asp', '50 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13191.asp', '1 рубль': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13244.asp'},
    '1982':{'1 копейка': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr11968.asp', '2 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12163.asp', '3 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12379.asp', '5 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12557.asp', '10 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12744.asp', '15 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12935.asp', '20 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13109.asp', '50 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13192.asp', '1 рубль': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13246.asp'},
    '1983':{'1 копейка': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr11970.asp', '2 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12164.asp', '3 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12382.asp', '5 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12558.asp', '10 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12746.asp', '15 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12937.asp', '20 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13113.asp', '50 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13193.asp', '1 рубль': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13247.asp'},
    '1984':{'1 копейка': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr11972.asp', '2 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12165.asp', '3 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12385.asp', '5 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12559.asp', '10 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12748.asp', '15 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12938.asp', '20 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13117.asp', '50 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13194.asp', '1 рубль': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13248.asp'},
    '1985':{'1 копейка': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr11974.asp', '2 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12166.asp', '3 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12388.asp', '5 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12560.asp', '10 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12750.asp', '15 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12940.asp', '20 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13119.asp', '50 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13195.asp', '1 рубль': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13249.asp'},
    '1986':{'1 копейка': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr11975.asp', '2 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12167.asp', '3 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12392.asp', '5 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12561.asp', '10 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12753.asp', '15 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12942.asp', '20 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13121.asp', '50 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13196.asp', '50 копеек гурт 1985': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13197.asp', '1 рубль': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13250.asp'},
    '1987':{'1 копейка': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr11976.asp', '2 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12169.asp', '3 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12396.asp', '5 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12562.asp', '10 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12756.asp', '15 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12944.asp', '20 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13124.asp', '50 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13198.asp', '1 рубль': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13251.asp'},
    '1988':{'1 копейка': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr11977.asp', '2 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12170.asp', '3 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12400.asp', '5 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12563.asp', '10 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12757.asp', '15 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12945.asp', '20 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13127.asp', '50 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13199.asp', '50 копеек гурт 1987': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13200.asp', '1 рубль': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13252.asp'},
    '1989':{'1 копейка': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr11979.asp', '2 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12172.asp', '3 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12403.asp', '5 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12565.asp', '10 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12759.asp', '15 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12947.asp', '20 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13131.asp', '50 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13202.asp', '1 рубль': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13254.asp'},
    '1990':{'1 копейка': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr11981.asp', '2 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12174.asp', '3 копейки': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12407.asp', '5 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12567.asp', '5 копеек буква М': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12569.asp', '10 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12760.asp', '10 копеек буква М': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12762.asp', '15 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12948.asp', '20 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13133.asp', '50 копеек': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13206.asp', '1 рубль': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13256.asp', '1 рубль гурт 1989': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13255.asp'},
    '1991':{'1 копейка Л': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr11983.asp', '1 копейка М': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr11984.asp', '2 копейки Л': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12176.asp', '2 копейки М': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12177.asp', '3 копейки Л': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12410.asp', '3 копейки М': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12411.asp', '5 копеек Л': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12570.asp', '5 копеек М': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12571.asp', '10 копеек без букв': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12763.asp', '10 копеек Л': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12764.asp', '10 копеек М': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12765.asp', '15 копеек Л': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12950.asp', '15 копеек М': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr12951.asp', '20 копеек без букв': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13136.asp', '20 копеек Л': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13137.asp', '20 копеек М': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13138.asp', '50 копеек Л': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13208.asp', '50 копеек М': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13209.asp', '1 рубль Л': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13257.asp', '1 рубль М': 'https://www.fcoins.ru/catalog/catalogussr/catalogussr13258.asp'}
}

def get_coin_url(year: str)->str:
    coin_url = coin_urls.get(year)
    return coin_url

def get_coin_price(url):
    result = requests.get(url)
    result.raise_for_status()
    soup = BeautifulSoup(result.content, 'html.parser')
    table_coins = soup.findAll('tr', class_='tr-mobile')
    safety = []
    price = []
    for coins in table_coins:
        safety.append(coins.find('b').text)
        price.append(coins.find('br').previous_element)
    safety_price = dict(zip(safety, price))
    return safety_price

    
